[WIP] Liquidation Pair V0
pooltogether/v5-liquidator pull request #1
Opened 2023-01-16 17:13 UTC by dylandesrosier

2023-01-18 19:42 UTC, asselstine requested changes

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPair.sol
> +    ILiquidationPairYieldSource public immutable liquidatorYieldSource; // Where to get tokenIn from
Let's keep the liquidator free of any concept of "yield".

- `ILiquidationPairYieldSource` could be renamed to `ILiquidationSource`
- all fields named `prizePool` could be renamed to `source`
- all fields named `liquidatorYieldSource` could be renamed to `source`

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPair.sol
> +        address indexed account,
The `prizePool` (wrong name?), `target`, `tokenIn` and `tokenOut` are immutable, so there is no need to emit them for every event. This event could be just the `account`, `amountIn` and `amountOut`

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPair.sol
> +    uint256 public virtualReserveOut;
Can we safely change `virtualReserveIn` and `virtualReserveOut` to each be 128 bits? Does that give us enough overhead? What kind of overhead do we require?

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPair.sol
> +        return liquidatorYieldSource.availableBalanceOf(address(tokenOut));
Can we apply the same optimization trick to avoid the extcodesize check:

https://github.com/Uniswap/v3-core/blob/05c10bf6d547d6121622ac51c457f93775e1df09/contracts/UniswapV3Pool.sol#L140

?

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPair.sol
> +        return (tokenIn, tokenOut, swapMultiplier, liquidityFraction);
No need for additional accessors here.  Can ✂️  these

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPair.sol
> +        return (virtualReserveIn, virtualReserveOut);
✂️ fields are already public

2023-01-18 19:42 UTC, asselstine commented on src/interfaces/ILiquidationPairYieldSource.sol
> +interface ILiquidationPairYieldSource {
Rename as liquidation source

2023-01-18 19:42 UTC, asselstine commented on src/libraries/LiquidatorLib.sol
> +        require(reserve0 > 0 && reserve1 > 0, "CpmmLib/INSUFF_PAIR_LIQ");
`CpmmLib` no longer exists; all errors should be renamed

2023-01-18 19:42 UTC, asselstine commented on src/libraries/LiquidatorLib.sol
> +        require(_amountOut1 <= _amountIn1, "insuff balance");
Should have an error code consistent with the rest, and as short as possible

2023-01-18 19:42 UTC, asselstine commented on src/libraries/LiquidatorLib.sol
> +        require(amountOut1 <= _amountIn1, "insuff balance");
ditto

2023-01-18 19:42 UTC, asselstine commented on README.md
> +> TODO: Coveralls tag, coverage
coverage tag 👍

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPairFactory.sol
> +        new LiquidationPair(_owner, _liquidatorYieldSource, _target,  _tokenIn, _tokenOut, _swapMultiplier, _liquidityFraction, _virtualReserveIn, _virtualReserveOut);
My linter wants better formatting here

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPairFactory.sol
> +        ILiquidationPairYieldSource indexed LiquidationPairYieldSource,
rename

2023-01-18 19:42 UTC, asselstine commented on src/LiquidationPairFactory.sol
> +        ILiquidationPairYieldSource _liquidatorYieldSource,
rename

2023-01-19 19:18 UTC, dylandesrosier commented on src/LiquidationPair.sol
> +        return liquidatorYieldSource.availableBalanceOf(address(tokenOut));
Only if that's how the `source` operates. It's on the `source` to implement `availableBalanceOf` and they might hold the tokens in a different contract.

2023-01-19 19:18 UTC, dylandesrosier commented on src/LiquidationPairFactory.sol
> +        new LiquidationPair(_owner, _liquidatorYieldSource, _target,  _tokenIn, _tokenOut, _swapMultiplier, _liquidityFraction, _virtualReserveIn, _virtualReserveOut);
I used the Forge formatter but it looks like we use Prettier everywhere else. I'll reformat the whole project with Prettier.

2023-02-02 17:53 UTC, merged